import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ThemeSelector } from "./ThemeSelector";
import { usePalettePreference } from "../models/themePreference";
import { CHARACTER_SHEET_BACKGROUNDS, useCharacterSheetBackground } from "../models/characterSheetBackground";
const PALETTES = [
    { value: "davokar", label: "Davokar", description: "Musgo, carbón y oro viejo" },
    { value: "corruption", label: "Corrupción", description: "Acero, ceniza y cobre" },
    { value: "ambria", label: "Ambria", description: "Burdeos, marfil y latón" }
];
export function AppearanceSelector() {
    const [palette, setPalette] = usePalettePreference();
    const [background, setBackground] = useCharacterSheetBackground();
    return (_jsxs("div", { className: "appearance-selector", children: [_jsxs("div", { className: "appearance-selector-heading", children: [_jsx("span", { children: "Atm\u00F3sfera" }), _jsx("small", { children: "La ambientaci\u00F3n no cambia la luminosidad." })] }), _jsx("div", { className: "palette-selector", role: "group", "aria-label": "Atm\u00F3sfera visual", children: PALETTES.map((option) => (_jsxs("button", { type: "button", className: palette === option.value ? "is-active" : "", "aria-pressed": palette === option.value, onClick: () => setPalette(option.value), children: [_jsxs("span", { className: "palette-swatch", "data-palette-swatch": option.value, "aria-hidden": "true", children: [_jsx("i", {}), _jsx("i", {}), _jsx("i", {})] }), _jsxs("span", { className: "palette-option-copy", children: [_jsx("strong", { children: option.label }), _jsx("small", { children: option.description })] })] }, option.value))) }), _jsxs("div", { className: "appearance-theme-section", children: [_jsx("span", { children: "Tema" }), _jsx(ThemeSelector, {})] }), _jsxs("div", { className: "appearance-background-section", children: [_jsxs("div", { className: "appearance-selector-heading", children: [_jsx("span", { children: "Fondo de pantalla" }), _jsx("small", { children: "La ilustraci\u00F3n elegida se comparte entre todas tus pantallas." })] }), _jsxs("div", { className: "appearance-background-selector", role: "group", "aria-label": "Fondo de pantalla", children: [_jsxs("button", { type: "button", className: `appearance-background-option is-none${background === "none" ? " is-active" : ""}`, "aria-pressed": background === "none", onClick: () => setBackground("none"), children: [_jsx("span", { className: "appearance-background-none", "aria-hidden": "true" }), _jsx("span", { children: "Sin ilustraci\u00F3n" })] }), CHARACTER_SHEET_BACKGROUNDS.map((option) => (_jsxs("button", { type: "button", className: background === option.id ? "is-active" : "", "aria-pressed": background === option.id, onClick: () => setBackground(option.id), children: [_jsx("img", { src: option.thumbnailUrl, alt: "", loading: "lazy" }), _jsx("span", { children: option.name })] }, option.id)))] })] })] }));
}
