ALTER TABLE "characters"
ADD COLUMN IF NOT EXISTS "culture" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "profession" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "sheet" JSONB NOT NULL DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
