import type { CharacterSheet } from "@umbra/shared";

type InventoryItem = CharacterSheet["inventoryItems"][number];

export type ItemTemplate = Omit<InventoryItem, "id" | "quantity" | "equipped"> & {
  templateId: string;
  defaultQuantity?: number;
};

export const ITEM_CATALOG: ItemTemplate[] = [
  {
    templateId: "weapon-dagger",
    name: "Daga",
    category: "weapon",
    stackable: false,
    isCustom: false,
    description: "Arma corta, facil de ocultar.",
    weight: "Ligera",
    value: "",
    slot: "offHand",
    attackAttribute: "diestro",
    damageFormula: "1d6",
    protectionFormula: "",
    qualities: "Corta",
    notes: "",
    grantedActions: [],
    modifiers: []
  },
  {
    templateId: "weapon-sword",
    name: "Espada larga",
    category: "weapon",
    stackable: false,
    isCustom: false,
    description: "Arma versatil de una mano.",
    weight: "Media",
    value: "",
    slot: "mainHand",
    attackAttribute: "diestro",
    damageFormula: "1d8",
    protectionFormula: "",
    qualities: "",
    notes: "",
    grantedActions: [],
    modifiers: []
  },
  {
    templateId: "weapon-spear",
    name: "Lanza",
    category: "weapon",
    stackable: false,
    isCustom: false,
    description: "Arma larga para mantener la distancia.",
    weight: "Media",
    value: "",
    slot: "mainHand",
    attackAttribute: "diestro",
    damageFormula: "1d10",
    protectionFormula: "",
    qualities: "Larga",
    notes: "",
    grantedActions: [],
    modifiers: []
  },
  {
    templateId: "weapon-bow",
    name: "Arco",
    category: "weapon",
    stackable: false,
    isCustom: false,
    description: "Arma a distancia comun.",
    weight: "Media",
    value: "",
    slot: "ranged",
    attackAttribute: "diestro",
    damageFormula: "1d8",
    protectionFormula: "",
    qualities: "A distancia",
    notes: "",
    grantedActions: [],
    modifiers: []
  },
  {
    templateId: "weapon-crossbow",
    name: "Ballesta",
    category: "weapon",
    stackable: false,
    isCustom: false,
    description: "Arma a distancia de gran pegada.",
    weight: "Media",
    value: "",
    slot: "ranged",
    attackAttribute: "diestro",
    damageFormula: "1d10",
    protectionFormula: "",
    qualities: "A distancia",
    notes: "",
    grantedActions: [],
    modifiers: []
  },
  {
    templateId: "weapon-throwing-knife",
    name: "Cuchillo arrojadizo",
    category: "weapon",
    stackable: true,
    isCustom: false,
    description: "Arma ligera para combate cercano o lanzamiento.",
    weight: "Ligera",
    value: "",
    slot: "none",
    attackAttribute: "diestro",
    damageFormula: "1d6",
    protectionFormula: "",
    qualities: "Arrojadiza, Corta",
    notes: "",
    grantedActions: [],
    modifiers: [],
    defaultQuantity: 3
  },
  {
    templateId: "armor-light",
    name: "Armadura ligera",
    category: "armor",
    stackable: false,
    isCustom: false,
    description: "Proteccion ligera de cuero o tejidos reforzados.",
    weight: "Ligera",
    value: "",
    slot: "armor",
    attackAttribute: undefined,
    damageFormula: "",
    protectionFormula: "1d4",
    qualities: "Ligera",
    notes: "",
    grantedActions: [],
    modifiers: []
  },
  {
    templateId: "armor-medium",
    name: "Armadura media",
    category: "armor",
    stackable: false,
    isCustom: false,
    description: "Proteccion media para combate sostenido.",
    weight: "Media",
    value: "",
    slot: "armor",
    attackAttribute: undefined,
    damageFormula: "",
    protectionFormula: "1d6",
    qualities: "Media, Incomoda",
    notes: "",
    grantedActions: [],
    modifiers: []
  },
  {
    templateId: "armor-heavy",
    name: "Armadura pesada",
    category: "armor",
    stackable: false,
    isCustom: false,
    description: "Proteccion pesada de placas o cota reforzada.",
    weight: "Pesada",
    value: "",
    slot: "armor",
    attackAttribute: undefined,
    damageFormula: "",
    protectionFormula: "1d8",
    qualities: "Pesada, Incomoda",
    notes: "",
    grantedActions: [],
    modifiers: []
  },
  {
    templateId: "armor-shield",
    name: "Escudo",
    category: "armor",
    stackable: false,
    isCustom: false,
    description: "Escudo para defensa cercana.",
    weight: "Media",
    value: "",
    slot: "offHand",
    attackAttribute: undefined,
    damageFormula: "",
    protectionFormula: "",
    qualities: "Escudo",
    notes: "",
    grantedActions: [],
    modifiers: [
      { id: "shield-defense", label: "Bonificacion de defensa", modifierType: "defense", value: "+1", notes: "Bonificacion base por llevar escudo." }
    ]
  },
  {
    templateId: "gear-backpack",
    name: "Mochila",
    category: "gear",
    stackable: false,
    isCustom: false,
    description: "Contenedor de viaje.",
    weight: "Ligera",
    value: "",
    slot: "none",
    attackAttribute: undefined,
    damageFormula: "",
    protectionFormula: "",
    qualities: "",
    notes: "",
    grantedActions: [],
    modifiers: []
  },
  {
    templateId: "gear-rations",
    name: "Raciones",
    category: "consumable",
    stackable: true,
    isCustom: false,
    description: "Comida para un dia de viaje.",
    weight: "Ligera",
    value: "",
    slot: "none",
    attackAttribute: undefined,
    damageFormula: "",
    protectionFormula: "",
    qualities: "",
    notes: "",
    grantedActions: [],
    modifiers: [],
    defaultQuantity: 3
  },
  {
    templateId: "gear-torch",
    name: "Antorcha",
    category: "consumable",
    stackable: true,
    isCustom: false,
    description: "Fuente de luz basica.",
    weight: "Ligera",
    value: "",
    slot: "none",
    attackAttribute: undefined,
    damageFormula: "",
    protectionFormula: "",
    qualities: "Luz",
    notes: "",
    grantedActions: [],
    modifiers: [],
    defaultQuantity: 3
  },
  {
    templateId: "gear-rope",
    name: "Cuerda",
    category: "gear",
    stackable: false,
    isCustom: false,
    description: "Cuerda de viaje o escalada.",
    weight: "Media",
    value: "",
    slot: "none",
    attackAttribute: undefined,
    damageFormula: "",
    protectionFormula: "",
    qualities: "",
    notes: "",
    grantedActions: [],
    modifiers: []
  },
  {
    templateId: "consumable-herbs",
    name: "Hierbas curativas",
    category: "consumable",
    stackable: true,
    isCustom: false,
    description: "Material de apoyo para curacion.",
    weight: "Ligera",
    value: "",
    slot: "none",
    attackAttribute: undefined,
    damageFormula: "",
    protectionFormula: "",
    qualities: "",
    notes: "",
    grantedActions: [
      {
        id: "usar-hierbas-curativas",
        label: "Usar hierbas curativas",
        cost: "combat",
        effectSummary: "Aplicar hierbas curativas sobre un objetivo."
      }
    ],
    modifiers: [],
    defaultQuantity: 2
  },
  {
    templateId: "consumable-elixir",
    name: "Elixir",
    category: "consumable",
    stackable: true,
    isCustom: false,
    description: "Consumible alquimico de uso rapido.",
    weight: "Ligera",
    value: "",
    slot: "none",
    attackAttribute: undefined,
    damageFormula: "",
    protectionFormula: "",
    qualities: "Alquimico",
    notes: "",
    grantedActions: [
      {
        id: "usar-elixir",
        label: "Usar elixir",
        cost: "movement",
        effectSummary: "Usar o aplicar el elixir sobre uno mismo o el equipo."
      }
    ],
    modifiers: [],
    defaultQuantity: 1
  },
  {
    templateId: "artifact-generic",
    name: "Artefacto",
    category: "artifact",
    stackable: false,
    isCustom: false,
    description: "Artefacto mistico de origen desconocido.",
    weight: "",
    value: "",
    slot: "artifact",
    attackAttribute: undefined,
    damageFormula: "",
    protectionFormula: "",
    qualities: "Mistico",
    notes: "",
    grantedActions: [],
    modifiers: []
  }
];

export function createInventoryItemFromTemplate(template: ItemTemplate): InventoryItem {
  return {
    ...template,
    id: `${template.templateId}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    quantity: template.defaultQuantity ?? 1,
    equipped: false
  };
}

export function createCustomInventoryItem(): InventoryItem {
  return {
    id: `custom-item-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    name: "Objeto personalizado",
    category: "gear",
    quantity: 1,
    stackable: false,
    isCustom: true,
    description: "",
    weight: "",
    value: "",
    equipped: false,
    slot: "none",
    attackAttribute: undefined,
    damageFormula: "",
    protectionFormula: "",
    qualities: "",
    notes: "",
    grantedActions: [],
    modifiers: []
  };
}
