import { buildWeaponCatalogNotes, WEAPON_QUALITY_OPTIONS, WEAPON_TEMPLATES, formatWeaponQualities } from "@umbra/shared";
export const ARMOR_QUALITY_OPTIONS = [
    { id: "ligera", label: "Ligera", summary: "Armadura de proteccion liviana y de uso cotidiano.", details: "Las armaduras ligeras priorizan movilidad y discrecion frente a la proteccion bruta." },
    { id: "media", label: "Media", summary: "Proteccion intermedia para combate sostenido.", details: "Las armaduras medias equilibran resistencia y movilidad, pero ya resultan mas aparatosas que las ligeras." },
    { id: "pesada", label: "Pesada", summary: "Armadura de guerra orientada a absorber castigo.", details: "Las armaduras pesadas ofrecen gran proteccion a cambio de incomodidad, coste y presencia evidente." },
    { id: "incomoda", label: "Incomoda", summary: "La armadura dificulta movimientos agiles y castiga ciertas maniobras.", details: "La cualidad Incomoda representa penalizacion por volumen, rigidez o peso distribuido sobre el cuerpo." },
    { id: "flexible", label: "Flexible", summary: "La armadura conserva movilidad y resulta menos torpe de llevar.", details: "Flexible indica materiales, cortes o ensamblajes que permiten moverse mejor que otras armaduras de proteccion similar." },
    { id: "reforzada", label: "Reforzada", summary: "La pieza anade placas, remaches o capas extra para mejorar su aguante.", details: "Reforzada representa una version mas resistente de la armadura base, normalmente con mayor proteccion o mejor cobertura." },
    { id: "oculta", label: "Oculta", summary: "Puede llevarse disimulada bajo la ropa o sin llamar demasiado la atencion.", details: "La armadura se integra en ropa, costuras o capas discretas para pasar mas facilmente desapercibida." },
    { id: "escudo", label: "Escudo", summary: "Proteccion defensiva secundaria llevada en la mano.", details: "Los escudos aportan defensa activa y suelen incluir bonificaciones o interacciones distintas a las de una armadura corporal." }
];
function buildArmorCatalogNotes(notes, qualities) {
    const definitionsByLabel = new Map(ARMOR_QUALITY_OPTIONS.map((quality) => [quality.label, quality]));
    const qualityNotes = qualities
        .map((quality) => definitionsByLabel.get(quality))
        .filter((entry) => Boolean(entry))
        .map((entry) => `${entry.label}: ${entry.details ?? entry.summary}`);
    return [notes.trim(), ...qualityNotes].filter(Boolean).join("\n");
}
const WEAPON_ITEM_TEMPLATES = WEAPON_TEMPLATES.map((template) => ({
    templateId: template.templateId,
    name: template.name,
    category: "weapon",
    stackable: template.stackable ?? false,
    isCustom: false,
    description: template.description,
    weight: template.weight,
    value: template.value,
    slot: template.slot,
    attackAttribute: template.attackAttribute,
    damageFormula: template.damageFormula,
    protectionFormula: "",
    qualities: formatWeaponQualities(template.qualities),
    notes: buildWeaponCatalogNotes(template.notes ?? "", template.qualities),
    grantedActions: [],
    modifiers: [],
    defaultQuantity: template.defaultQuantity
}));
const OTHER_ITEM_TEMPLATES = [
    {
        templateId: "armor-light",
        name: "Armadura ligera",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Proteccion ligera de cuero o tejidos reforzados.",
        weight: "Ligera",
        value: "",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4",
        qualities: "Ligera",
        notes: buildArmorCatalogNotes("Ref: Libro Basico p. 150.", ["Ligera"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-woven-silk",
        name: "Seda tejida",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Vestidura reforzada con capas y bordados resistentes, popular entre quienes quieren protegerse sin parecer acorazados.",
        weight: "Ligera",
        value: "10 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4",
        qualities: "Ligera, Flexible",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 113.", ["Ligera", "Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-witch-gown",
        name: "Toga de bruja",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Tunica ceremonial de telas superpuestas y protecciones discretas, habitual entre misticos que rehuyen la armadura militar.",
        weight: "Ligera",
        value: "10 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4",
        qualities: "Ligera, Flexible",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 113.", ["Ligera", "Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-studded-leather",
        name: "Cuero tachonado",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Cuero endurecido con remaches y placas pequenas para soportar mejor los impactos.",
        weight: "Ligera",
        value: "10 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4+1",
        qualities: "Ligera, Reforzada",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 113.", ["Ligera", "Reforzada"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-skald-cuirass",
        name: "Coselete de skald",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Coraza ornamentada y flexible, preparada para duelos, viajes y apariciones publicas sin sacrificar demasiada proteccion.",
        weight: "Ligera",
        value: "50 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4+1",
        qualities: "Ligera, Reforzada, Flexible",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 113.", ["Ligera", "Reforzada", "Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-wolfskin",
        name: "Piel de lobo",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Piel gruesa y capas bastas empleadas por barbaros y cazadores, mas tosca que elegante.",
        weight: "Ligera",
        value: "1 talero",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4",
        qualities: "Ligera, Incomoda",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 113.", ["Ligera", "Incomoda"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-concealed",
        name: "Armadura oculta",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Proteccion discreta cosida bajo jubones o ropas nobles para sobrevivir a emboscadas y duelos inesperados.",
        weight: "Ligera",
        value: "50 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4",
        qualities: "Ligera, Oculta, Flexible",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 113.", ["Ligera", "Oculta", "Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-blessed-robe",
        name: "Ropajes benditos",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Vestiduras santificadas y reforzadas con simbolos sagrados, apreciadas por teurgos y guardianes de templos.",
        weight: "Ligera",
        value: "10 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4",
        qualities: "Ligera, Flexible",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 113.", ["Ligera", "Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-medium",
        name: "Armadura media",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Proteccion media para combate sostenido.",
        weight: "Media",
        value: "",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d6",
        qualities: "Media, Incomoda",
        notes: buildArmorCatalogNotes("Ref: Libro Basico p. 150.", ["Media", "Incomoda"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-double-chain",
        name: "Cota doble",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Malla densa y doblada sobre las zonas vitales para mejorar la cobertura sin llegar a una coraza pesada.",
        weight: "Media",
        value: "125 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d6+1",
        qualities: "Media, Reforzada, Flexible",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 113.", ["Media", "Reforzada", "Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-crow",
        name: "Armadura de cuervo",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Manto de plumas, cuero y piezas oscuras que protege con eficacia y proyecta un aspecto ominoso.",
        weight: "Media",
        value: "2 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d6",
        qualities: "Media, Incomoda",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 113.", ["Media", "Incomoda"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-lacquered-silk",
        name: "Coraza de seda lacada",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Coraza de placas ligeras y seda endurecida, tipica de guerreros que valoran la disciplina y la movilidad.",
        weight: "Media",
        value: "25 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d6",
        qualities: "Media, Flexible",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 113.", ["Media", "Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-laminated",
        name: "Armadura laminada",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Laminas y capas superpuestas para aumentar la resistencia sin el coste de una armadura de placas completa.",
        weight: "Media",
        value: "25 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d6+1",
        qualities: "Media, Reforzada",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 113.", ["Media", "Reforzada"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-heavy",
        name: "Armadura pesada",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Proteccion pesada de placas o cota reforzada.",
        weight: "Pesada",
        value: "",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d8",
        qualities: "Pesada, Incomoda",
        notes: buildArmorCatalogNotes("Ref: Libro Basico p. 150.", ["Pesada", "Incomoda"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-field",
        name: "Armadura de campana",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Armadura militar robusta para lineas de frente, asedios y marchas de guerra.",
        weight: "Pesada",
        value: "50 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d8+1",
        qualities: "Pesada, Reforzada",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 113.", ["Pesada", "Reforzada"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-full-plate",
        name: "Armadura de placas",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Conjunto de placas articuladas para caballeros, campeones y guardianes de elite.",
        weight: "Pesada",
        value: "50 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d8",
        qualities: "Pesada, Flexible",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 113.", ["Pesada", "Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-pansar-field",
        name: "Armadura pansar de campana",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Version de elite de la armadura de campana, fabricada para tropas pesadas de alto rango.",
        weight: "Pesada",
        value: "250 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d8+1",
        qualities: "Pesada, Reforzada, Flexible",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 113.", ["Pesada", "Reforzada", "Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-shield",
        name: "Escudo",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Escudo para defensa cercana.",
        weight: "Media",
        value: "3 taleros",
        slot: "offHand",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Escudo",
        notes: buildArmorCatalogNotes("Ref: Libro Basico p. 150.", ["Escudo"]),
        grantedActions: [],
        modifiers: [
            { id: "shield-defense", label: "Bonificacion de defensa", modifierType: "defense", value: "+1", notes: "Bonificacion base por llevar escudo." }
        ]
    },
    {
        templateId: "gear-backpack",
        name: "Mochila",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Contenedor de viaje.",
        weight: "Ligera",
        value: "",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "",
        notes: "",
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "gear-rations",
        name: "Raciones",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Comida para un dia de viaje.",
        weight: "Ligera",
        value: "",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "",
        notes: "",
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 3
    },
    {
        templateId: "gear-torch",
        name: "Antorcha",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Fuente de luz basica.",
        weight: "Ligera",
        value: "",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Luz",
        notes: "",
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 3
    },
    {
        templateId: "gear-rope",
        name: "Cuerda",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Cuerda de viaje o escalada.",
        weight: "Media",
        value: "",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "",
        notes: "",
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "consumable-herbs",
        name: "Hierbas curativas",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Material de apoyo para curacion.",
        weight: "Ligera",
        value: "",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "",
        notes: "",
        grantedActions: [
            {
                id: "usar-hierbas-curativas",
                label: "Usar hierbas curativas",
                cost: "combat",
                effectSummary: "Aplicar hierbas curativas sobre un objetivo."
            }
        ],
        modifiers: [],
        defaultQuantity: 2
    },
    {
        templateId: "consumable-elixir",
        name: "Elixir",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Consumible alquimico de uso rapido.",
        weight: "Ligera",
        value: "",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Alquimico",
        notes: "",
        grantedActions: [
            {
                id: "usar-elixir",
                label: "Usar elixir",
                cost: "movement",
                effectSummary: "Usar o aplicar el elixir sobre uno mismo o el equipo."
            }
        ],
        modifiers: [],
        defaultQuantity: 1
    },
    {
        templateId: "artifact-generic",
        name: "Artefacto",
        category: "artifact",
        stackable: false,
        isCustom: false,
        description: "Artefacto mistico de origen desconocido.",
        weight: "",
        value: "",
        slot: "artifact",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Mistico",
        notes: "",
        grantedActions: [],
        modifiers: []
    }
];
export const ITEM_CATALOG = [...WEAPON_ITEM_TEMPLATES, ...OTHER_ITEM_TEMPLATES];
export { WEAPON_QUALITY_OPTIONS };
export function createInventoryItemFromTemplate(template) {
    return {
        ...template,
        id: `${template.templateId}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        quantity: template.defaultQuantity ?? 1,
        equipped: false
    };
}
export function createCustomInventoryItem(category = "gear") {
    const isWeapon = category === "weapon";
    const isArmor = category === "armor";
    return {
        id: `custom-item-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        name: isWeapon ? "Arma personalizada" : isArmor ? "Armadura personalizada" : "Objeto personalizado",
        category,
        quantity: 1,
        stackable: false,
        isCustom: true,
        description: "",
        weight: "",
        value: "",
        equipped: false,
        slot: isWeapon ? "mainHand" : isArmor ? "armor" : "none",
        attackAttribute: isWeapon ? "diestro" : undefined,
        damageFormula: "",
        protectionFormula: isArmor ? "1d4" : "",
        qualities: isArmor ? "Ligera" : "",
        notes: "",
        grantedActions: [],
        modifiers: []
    };
}
