import { buildWeaponCatalogNotes, WEAPON_QUALITY_OPTIONS, WEAPON_TEMPLATES, formatWeaponQualities } from "@umbra/shared";
export const ARMOR_QUALITY_OPTIONS = [
    { id: "ligera", label: "Ligera", summary: "Armadura de proteccion liviana y de uso cotidiano.", details: "Las armaduras ligeras priorizan movilidad y discrecion frente a la proteccion bruta." },
    { id: "media", label: "Media", summary: "Proteccion intermedia para combate sostenido.", details: "Las armaduras medias equilibran resistencia y movilidad, pero ya resultan mas aparatosas que las ligeras." },
    { id: "pesada", label: "Pesada", summary: "Armadura de guerra orientada a absorber castigo.", details: "Las armaduras pesadas ofrecen gran proteccion a cambio de incomodidad, coste y presencia evidente." },
    { id: "incomoda", label: "Incómoda", summary: "Penaliza Defensa, sigilo y uso de poderes misticos segun el tipo.", details: "Impone -2 si es ligera, -3 si es media y -4 si es pesada a Defensa, sigilo y uso de poderes misticos." },
    { id: "aparatosa", label: "Aparatosa", summary: "Penaliza un punto mas que una armadura Incomoda.", details: "Impone -3 si es ligera, -4 si es media y -5 si es pesada a Defensa, sigilo y uso de poderes misticos." },
    { id: "flexible", label: "Flexible", summary: "Reduce en dos puntos la penalizacion del tipo de armadura.", details: "Una armadura Flexible no penaliza si es ligera, impone -1 si es media y -2 si es pesada." },
    { id: "reforzada", label: "Reforzada", summary: "Suma +1 a las tiradas de armadura.", details: "La armadura es mas resistente que otras de su categoria y suma +1 a sus tiradas de proteccion; el catalogo ya lo incluye en la formula." },
    { id: "oculta", label: "Oculta", summary: "Puede llevarse disimulada bajo la ropa o sin llamar demasiado la atencion.", details: "La armadura se integra en ropa, costuras o capas discretas para pasar mas facilmente desapercibida." },
    { id: "sagrada", label: "Sagrada", summary: "Puede obtener +1D4 de proteccion contra atacantes corruptos.", details: "Tras un ataque exitoso, la corrupcion del atacante determina si la armadura obtiene +1D4 de proteccion adicional." },
    { id: "retributiva", label: "Retributiva", summary: "Puede salpicar con acido a quien ataque cuerpo a cuerpo.", details: "Al defender cuerpo a cuerpo, el atacante debe superar Agil o sufrir 1D4 de daño por acido durante 1D4 turnos." }
];
export const ITEM_QUALITY_OPTIONS = [
    { id: "municion", label: "Municion", summary: "Se consume o agrupa como proyectiles o cargas.", details: "Incluye flechas, virotes, balas, piedras de honda y otros suministros para armas a distancia." },
    { id: "viaje", label: "Viaje", summary: "Equipo pensado para expediciones, campamentos y desplazamientos.", details: "Objetos utiles durante marchas, descansos, exploracion y vida al aire libre." },
    { id: "herramienta", label: "Herramienta", summary: "Utensilio tecnico para tareas concretas.", details: "Sirve para abrir, reparar, fabricar, medir o manipular objetos y entornos." },
    { id: "contenedor", label: "Contenedor", summary: "Permite guardar y transportar otros objetos.", details: "Bolsas, mochilas, sacos y recipientes que organizan o protegen el equipo." },
    { id: "luz", label: "Luz", summary: "Produce o sostiene iluminacion.", details: "Antorchas, linternas, velas, aceites y otros focos de luz para viaje y exploracion." },
    { id: "curacion", label: "Curacion", summary: "Se usa para estabilizar, tratar o recuperar salud.", details: "Hierbas, vendajes, ungüentos y preparados destinados a primeros auxilios o recuperacion." },
    { id: "alquimico", label: "Alquimico", summary: "Preparado alquimico de uso practico o medicinal.", details: "Sustancias refinadas, elixires y compuestos con aplicacion inmediata o tecnica." },
    { id: "material", label: "Material", summary: "Insumo para oficios, rituales o fabricacion.", details: "Materias primas, reactivos y componentes aprovechables en elaboracion o comercio." },
    { id: "ritual", label: "Ritual", summary: "Utilizado para ceremonias, simbolos o practicas misticas.", details: "Tintas, polvos, velas, reliquias y otros objetos ligados a ritos o preparacion espiritual." },
    { id: "mistico", label: "Mistico", summary: "Objeto con afinidad o procedencia sobrenatural.", details: "Piezas tocadas por fuerzas misticas, reliquias o implementos con resonancia espiritual." },
    { id: "veneno", label: "Veneno", summary: "Sustancia toxica para aplicar o mezclar.", details: "Compuestos dañinos usados en trampas, armas o intrigas discretas." },
    { id: "escritura", label: "Escritura", summary: "Sirve para registrar, estudiar o copiar informacion.", details: "Pergaminos, tinta, plumas y materiales de escribania o aprendizaje." },
    { id: "valioso", label: "Valioso", summary: "Mercancia o pieza de valor economico directo.", details: "Joyas, reliquias menores, lingotes, gemas y objetos cuyo fin principal es su valor." }
];
function buildArmorCatalogNotes(notes, qualities) {
    const definitionsByLabel = new Map(ARMOR_QUALITY_OPTIONS.map((quality) => [quality.label, quality]));
    const qualityNotes = qualities
        .map((quality) => definitionsByLabel.get(quality))
        .filter((entry) => Boolean(entry))
        .map((entry) => `${entry.label}: ${entry.details ?? entry.summary}`);
    return [notes.trim(), ...qualityNotes].filter(Boolean).join("\n");
}
function buildItemCatalogNotes(notes, qualities) {
    const definitionsByLabel = new Map(ITEM_QUALITY_OPTIONS.map((quality) => [quality.label, quality]));
    const qualityNotes = qualities
        .map((quality) => definitionsByLabel.get(quality))
        .filter((entry) => Boolean(entry))
        .map((entry) => `${entry.label}: ${entry.details ?? entry.summary}`);
    return [notes.trim(), ...qualityNotes].filter(Boolean).join("\n");
}
const WEAPON_ITEM_TEMPLATES = WEAPON_TEMPLATES.map((template) => ({
    templateId: template.templateId,
    name: template.name,
    category: "weapon",
    stackable: template.stackable ?? false,
    isCustom: false,
    description: template.description,
    weight: template.weight,
    value: template.value,
    slot: template.slot,
    attackAttribute: template.attackAttribute,
    damageFormula: template.damageFormula,
    protectionFormula: "",
    qualities: formatWeaponQualities(template.qualities),
    notes: buildWeaponCatalogNotes(template.notes ?? "", template.qualities),
    grantedActions: [],
    modifiers: template.defenseBonus
        ? [{ id: `${template.templateId}-defense`, label: "Bonificacion de escudo", modifierType: "defense", value: `+${template.defenseBonus}`, notes: "Bonificacion base por llevar el escudo equipado." }]
        : [],
    defaultQuantity: template.defaultQuantity
}));
const OTHER_ITEM_TEMPLATES = [
    {
        templateId: "armor-light",
        name: "Armadura ligera",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Proteccion ligera de cuero o tejidos reforzados.",
        weight: "Ligera",
        value: "2 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4",
        qualities: "Incómoda",
        notes: buildArmorCatalogNotes("Ref: Libro Basico p. 150.", ["Incómoda"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-woven-silk",
        name: "Hilo de seda",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Vestidura reforzada con capas y bordados resistentes, popular entre quienes quieren protegerse sin parecer acorazados.",
        weight: "Ligera",
        value: "10 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4",
        qualities: "Flexible",
        notes: buildArmorCatalogNotes("Ref: Libro Basico p. 150.", ["Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-witch-gown",
        name: "Ropajes de bruja",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Tunica ceremonial de telas superpuestas y protecciones discretas, habitual entre misticos que rehuyen la armadura militar.",
        weight: "Ligera",
        value: "10 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4",
        qualities: "Flexible",
        notes: buildArmorCatalogNotes("Ref: Libro Basico p. 150.", ["Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-studded-leather",
        name: "Cuero tachonado",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Cuero endurecido con remaches y placas pequeñas para soportar mejor los impactos.",
        weight: "Ligera",
        value: "10 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4+1",
        qualities: "Reforzada",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 117.", ["Reforzada"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-skald-cuirass",
        name: "Coraza de escaldo",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Coraza ornamentada y flexible, preparada para duelos, viajes y apariciones publicas sin sacrificar demasiada proteccion.",
        weight: "Ligera",
        value: "50 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4+1",
        qualities: "Reforzada, Flexible",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 117.", ["Reforzada", "Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-wolfskin",
        name: "Piel de lobo",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Piel gruesa y capas bastas empleadas por barbaros y cazadores, mas tosca que elegante.",
        weight: "Ligera",
        value: "1 talero",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4",
        qualities: "Aparatosa",
        notes: buildArmorCatalogNotes("Ref: Libro Basico p. 150-151.", ["Aparatosa"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-concealed",
        name: "Armadura oculta",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Proteccion discreta cosida bajo jubones o ropas nobles para sobrevivir a emboscadas y duelos inesperados.",
        weight: "Ligera",
        value: "50 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4",
        qualities: "Oculta, Flexible",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 116-117.", ["Oculta", "Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-order-cloak",
        name: "Capa de la Ordo",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Capa bordada con runas de proteccion que la Ordo Magica entrega a sus novicios.",
        weight: "Ligera",
        value: "10 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4",
        qualities: "Flexible",
        notes: buildArmorCatalogNotes("Ref: Libro Basico p. 150.", ["Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-blessed-robe",
        name: "Túnica bendita",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Vestiduras santificadas y reforzadas con simbolos sagrados, apreciadas por teurgos y guardianes de templos.",
        weight: "Ligera",
        value: "10 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d4",
        qualities: "Flexible",
        notes: buildArmorCatalogNotes("Ref: Libro Basico p. 150.", ["Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-medium",
        name: "Armadura media",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Proteccion media para combate sostenido.",
        weight: "Media",
        value: "5 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d6",
        qualities: "Incómoda",
        notes: buildArmorCatalogNotes("Ref: Libro Basico p. 150.", ["Incómoda"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-double-chain",
        name: "Cota de malla de doble",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Malla densa y doblada sobre las zonas vitales para mejorar la cobertura sin llegar a una coraza pesada.",
        weight: "Media",
        value: "125 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d6+1",
        qualities: "Reforzada, Flexible",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 117.", ["Reforzada", "Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-crow",
        name: "Armadura de cuervo",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Manto de plumas, cuero y piezas oscuras que protege con eficacia y proyecta un aspecto ominoso.",
        weight: "Media",
        value: "2 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d6",
        qualities: "Aparatosa",
        notes: buildArmorCatalogNotes("Ref: Libro Basico p. 150-151.", ["Aparatosa"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-lacquered-silk",
        name: "Coraza de seda lacada",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Coraza de placas ligeras y seda endurecida, tipica de guerreros que valoran la disciplina y la movilidad.",
        weight: "Media",
        value: "25 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d6",
        qualities: "Flexible",
        notes: buildArmorCatalogNotes("Ref: Libro Basico p. 150.", ["Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-laminated",
        name: "Armadura lamelar",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Laminas y capas superpuestas para aumentar la resistencia sin el coste de una armadura de placas completa.",
        weight: "Media",
        value: "25 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d6+1",
        qualities: "Reforzada",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 116-118.", ["Reforzada"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-heavy",
        name: "Armadura pesada",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Proteccion pesada de placas o cota reforzada.",
        weight: "Pesada",
        value: "10 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d8",
        qualities: "Incómoda",
        notes: buildArmorCatalogNotes("Ref: Libro Basico p. 150.", ["Incómoda"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-templar-full",
        name: "Armadura completa de templario",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Armadura completa forjada y bendecida para el circulo interno de los Caballeros del Sol Moribundo.",
        weight: "Pesada",
        value: "100 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d8+1",
        qualities: "Sagrada",
        notes: buildArmorCatalogNotes("Puede obtener +1d4 de proteccion adicional contra un atacante corrupto. Ref: Guia Avanzada del Jugador p. 116 y 119.", ["Sagrada"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-fury",
        name: "Armadura de la furia",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Cota de malla reforzada con energias vengativas de la Guardia de la Furia Dormida.",
        weight: "Pesada",
        value: "100 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d8",
        qualities: "Retributiva",
        notes: buildArmorCatalogNotes("Al defender cuerpo a cuerpo, el atacante debe superar Agil o sufrir 1d4 de daño por acido durante 1d4 turnos. Ref: Guia Avanzada del Jugador p. 116 y 119.", ["Retributiva"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-field",
        name: "Armadura de placas",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Armadura militar robusta para lineas de frente, asedios y marchas de guerra.",
        weight: "Pesada",
        value: "50 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d8+1",
        qualities: "Reforzada",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 116-118.", ["Reforzada"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-full-plate",
        name: "Armadura completa",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Conjunto de placas articuladas para caballeros, campeones y guardianes de elite.",
        weight: "Pesada",
        value: "50 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d8",
        qualities: "Flexible",
        notes: buildArmorCatalogNotes("Ref: Libro Basico p. 150.", ["Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "armor-pansar-field",
        name: "Armadura de placas pansar",
        category: "armor",
        stackable: false,
        isCustom: false,
        description: "Version de elite de la armadura de campaña, fabricada para tropas pesadas de alto rango.",
        weight: "Pesada",
        value: "250 taleros",
        slot: "armor",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "1d8+1",
        qualities: "Reforzada, Flexible",
        notes: buildArmorCatalogNotes("Ref: Guia Avanzada del Jugador p. 116-118.", ["Reforzada", "Flexible"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "gear-backpack",
        name: "Mochila",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Contenedor de viaje.",
        weight: "Ligera",
        value: "",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Contenedor, Viaje",
        notes: buildItemCatalogNotes("Ref: equipo de viaje basico.", ["Contenedor", "Viaje"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "gear-sack",
        name: "Saco",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Bolsa resistente para grano, botin o equipo de marcha.",
        weight: "Ligera",
        value: "5 ortegs",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Contenedor",
        notes: buildItemCatalogNotes("Contenedor basico para transporte.", ["Contenedor"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "gear-bandolier",
        name: "Bandolera",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Correa con bolsillos para organizar viales, municion o herramientas pequeñas.",
        weight: "Ligera",
        value: "1 talero",
        slot: "worn",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Contenedor",
        notes: buildItemCatalogNotes("Ref: equipo de viaje y exploracion.", ["Contenedor"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "gear-rations",
        name: "Raciones",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Comida para un dia de viaje.",
        weight: "Ligera",
        value: "",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Viaje",
        notes: buildItemCatalogNotes("Comida para un dia de viaje.", ["Viaje"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 3
    },
    {
        templateId: "gear-waterskin",
        name: "Odre",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Recipiente de cuero para agua, vino u otros liquidos de marcha.",
        weight: "Ligera",
        value: "5 ortegs",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Viaje, Contenedor",
        notes: buildItemCatalogNotes("Equipo comun de viaje.", ["Viaje", "Contenedor"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "gear-torch",
        name: "Antorcha",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Fuente de luz basica.",
        weight: "Ligera",
        value: "",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Luz",
        notes: buildItemCatalogNotes("Fuente de luz basica para exploracion y guardias.", ["Luz"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 3
    },
    {
        templateId: "gear-lantern",
        name: "Linterna",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Linterna protegida para iluminar sin exponer la llama directamente al viento.",
        weight: "Ligera",
        value: "2 taleros",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Luz, Viaje",
        notes: buildItemCatalogNotes("Suele necesitar aceite para varias horas de uso.", ["Luz", "Viaje"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "consumable-lamp-oil",
        name: "Aceite de lampara",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Reserva de aceite para lamparas, linternas o incendios deliberados.",
        weight: "Ligera",
        value: "5 ortegs",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Luz, Material, Alquimico",
        notes: buildItemCatalogNotes("Liquido inflamable util como combustible o accelerante.", ["Luz", "Material", "Alquimico"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 2
    },
    {
        templateId: "gear-rope",
        name: "Cuerda",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Cuerda de viaje o escalada.",
        weight: "Media",
        value: "",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Viaje, Herramienta",
        notes: buildItemCatalogNotes("Util para escalada, campamento o asegurar carga.", ["Viaje", "Herramienta"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "gear-grappling-hook",
        name: "Garfio",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Gancho de hierro para trepar, sujetar cuerdas o enganchar bordes.",
        weight: "Ligera",
        value: "1 talero",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Herramienta, Viaje",
        notes: buildItemCatalogNotes("Suele combinarse con cuerda para asaltos y exploracion.", ["Herramienta", "Viaje"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "gear-flint-steel",
        name: "Pedernal y eslabon",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Kit para encender fuego en condiciones razonables.",
        weight: "Ligera",
        value: "5 ortegs",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Herramienta, Viaje",
        notes: buildItemCatalogNotes("Base para prender antorchas, hornillos o hogueras.", ["Herramienta", "Viaje"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "gear-bedroll",
        name: "Manta de viaje",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Manta enrollada para dormir al raso o amortiguar terreno duro.",
        weight: "Media",
        value: "1 talero",
        slot: "worn",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Viaje",
        notes: buildItemCatalogNotes("Equipo de campamento simple.", ["Viaje"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "gear-tent",
        name: "Tienda ligera",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Refugio plegable para protegerse del clima durante expediciones.",
        weight: "Media",
        value: "3 taleros",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Viaje, Contenedor",
        notes: buildItemCatalogNotes("Equipo de campamento para descanso y resguardo.", ["Viaje", "Contenedor"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "consumable-arrows",
        name: "Flechas",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Municion comun para arcos y variantes similares.",
        weight: "Ligera",
        value: "1 talero",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Municion",
        notes: buildItemCatalogNotes("Paquete de proyectiles para arco.", ["Municion"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 10
    },
    {
        templateId: "consumable-bolts",
        name: "Virotes",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Municion corta y pesada para ballestas y arbalestas.",
        weight: "Ligera",
        value: "1 talero",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Municion",
        notes: buildItemCatalogNotes("Paquete de virotes para armas de perno.", ["Municion"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 10
    },
    {
        templateId: "consumable-sling-stones",
        name: "Piedras de honda",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Municion simple para hondas, llevada en saquitos o bolsillos.",
        weight: "Ligera",
        value: "2 ortegs",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Municion",
        notes: buildItemCatalogNotes("Suministro comun de proyectiles para honda.", ["Municion"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 20
    },
    {
        templateId: "consumable-darts",
        name: "Dardos",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Pequeños proyectiles para cerbatanas y trucos de veneno.",
        weight: "Ligera",
        value: "5 ortegs",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Municion, Material",
        notes: buildItemCatalogNotes("Puede usarse limpio o impregnado con toxinas.", ["Municion", "Material"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 10
    },
    {
        templateId: "consumable-herbs",
        name: "Hierbas curativas",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Material de apoyo para curacion.",
        weight: "Ligera",
        value: "",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Curacion, Material",
        notes: buildItemCatalogNotes("Material de apoyo para curacion.", ["Curacion", "Material"]),
        grantedActions: [
            {
                id: "usar-hierbas-curativas",
                label: "Usar hierbas curativas",
                cost: "combat",
                effectSummary: "Aplicar hierbas curativas sobre un objetivo."
            }
        ],
        modifiers: [],
        defaultQuantity: 2
    },
    {
        templateId: "consumable-elixir",
        name: "Elixir",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Consumible alquimico de uso rapido.",
        weight: "Ligera",
        value: "",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Alquimico",
        notes: buildItemCatalogNotes("Consumible alquimico de uso rapido.", ["Alquimico"]),
        grantedActions: [
            {
                id: "usar-elixir",
                label: "Usar elixir",
                cost: "movement",
                effectSummary: "Usar o aplicar el elixir sobre uno mismo o el equipo."
            }
        ],
        modifiers: [],
        defaultQuantity: 1
    },
    {
        templateId: "consumable-bandages",
        name: "Vendajes",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Tiras limpias para detener hemorragias y envolver heridas.",
        weight: "Ligera",
        value: "5 ortegs",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Curacion",
        notes: buildItemCatalogNotes("Util en primeros auxilios y cuidado de campo.", ["Curacion"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 3
    },
    {
        templateId: "consumable-antitoxin",
        name: "Antidoto",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Preparado para contrarrestar toxinas leves o estabilizar a un envenenado.",
        weight: "Ligera",
        value: "5 taleros",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Curacion, Alquimico",
        notes: buildItemCatalogNotes("Preparado alquimico contra venenos comunes.", ["Curacion", "Alquimico"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 1
    },
    {
        templateId: "consumable-poison",
        name: "Veneno",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Toxina preparada para untar armas, mezclar en comida o aplicar con herramientas finas.",
        weight: "Ligera",
        value: "10 taleros",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Veneno, Alquimico",
        notes: buildItemCatalogNotes("Sustancia peligrosa para intriga o asesinato.", ["Veneno", "Alquimico"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 1
    },
    {
        templateId: "gear-lockpicks",
        name: "Ganzuas",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Juego de herramientas finas para cerraduras, pestillos y mecanismos simples.",
        weight: "Ligera",
        value: "2 taleros",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Herramienta",
        notes: buildItemCatalogNotes("Equipo especializado para abrir cerraduras.", ["Herramienta"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "gear-crowbar",
        name: "Palanca",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Barra de hierro para forzar cajas, puertas y tapas pesadas.",
        weight: "Media",
        value: "1 talero",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Herramienta",
        notes: buildItemCatalogNotes("Ayuda a hacer palanca o abrir contenedores resistentes.", ["Herramienta"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "gear-fishing-kit",
        name: "Kit de pesca",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Linea, anzuelos y utensilios para obtener alimento en caminos y riberas.",
        weight: "Ligera",
        value: "1 talero",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Herramienta, Viaje",
        notes: buildItemCatalogNotes("Herramienta util para supervivencia y campamento.", ["Herramienta", "Viaje"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "gear-writing-kit",
        name: "Kit de escribania",
        category: "gear",
        stackable: false,
        isCustom: false,
        description: "Plumas, tinta, cuchilla y accesorios para copiar, registrar y estudiar.",
        weight: "Ligera",
        value: "2 taleros",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Escritura, Herramienta",
        notes: buildItemCatalogNotes("Material para escribir, copiar mapas o anotar rituales.", ["Escritura", "Herramienta"]),
        grantedActions: [],
        modifiers: []
    },
    {
        templateId: "consumable-parchment",
        name: "Pergamino y tinta",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Hojas y tinta para notas, cartas, cuentas o bosquejos rapidos.",
        weight: "Ligera",
        value: "5 ortegs",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Escritura, Material",
        notes: buildItemCatalogNotes("Suministro gastable de escribania.", ["Escritura", "Material"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 3
    },
    {
        templateId: "material-charcoal",
        name: "Carbon y yesca",
        category: "other",
        stackable: true,
        isCustom: false,
        description: "Material comun para encendido, marcado y trabajos rapidos.",
        weight: "Ligera",
        value: "2 ortegs",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Material, Viaje",
        notes: buildItemCatalogNotes("Insumo barato para fuego y marcas.", ["Material", "Viaje"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 2
    },
    {
        templateId: "material-thistle-powder",
        name: "Polvo de cardo",
        category: "other",
        stackable: true,
        isCustom: false,
        description: "Ingrediente alquimico y herbal usado en preparados de resistencia y mezclas rituales.",
        weight: "Ligera",
        value: "1 talero",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Material, Alquimico",
        notes: buildItemCatalogNotes("Ingrediente comun en preparaciones alquimicas.", ["Material", "Alquimico"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 1
    },
    {
        templateId: "material-quicksilver",
        name: "Mercurio",
        category: "other",
        stackable: true,
        isCustom: false,
        description: "Metal liquido valioso y peligroso, empleado en alquimia y procedimientos delicados.",
        weight: "Ligera",
        value: "3 taleros",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Material, Alquimico",
        notes: buildItemCatalogNotes("Reactivo costoso para laboratorio y ritual.", ["Material", "Alquimico"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 1
    },
    {
        templateId: "material-sulfur",
        name: "Azufre",
        category: "other",
        stackable: true,
        isCustom: false,
        description: "Reactivo mineral utilizado en humos, mezclas alquimicas y sustancias agresivas.",
        weight: "Ligera",
        value: "1 talero",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Material, Alquimico",
        notes: buildItemCatalogNotes("Ingrediente comun para preparados reactivos.", ["Material", "Alquimico"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 1
    },
    {
        templateId: "material-ritual-chalk",
        name: "Tiza ritual",
        category: "other",
        stackable: true,
        isCustom: false,
        description: "Tiza y polvos para marcar circulos, glifos y sellos temporales.",
        weight: "Ligera",
        value: "5 ortegs",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Material, Ritual",
        notes: buildItemCatalogNotes("Util para simbolos, marcas y procedimientos misticos.", ["Material", "Ritual"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 2
    },
    {
        templateId: "material-incense",
        name: "Incienso",
        category: "consumable",
        stackable: true,
        isCustom: false,
        description: "Resinas y aromas para ceremonias, cultos o purificaciones.",
        weight: "Ligera",
        value: "1 talero",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Ritual, Material",
        notes: buildItemCatalogNotes("Frecuente en liturgias, invocaciones o bendiciones.", ["Ritual", "Material"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 2
    },
    {
        templateId: "treasure-jewelry",
        name: "Joyas",
        category: "treasure",
        stackable: true,
        isCustom: false,
        description: "Piezas pequeñas de valor que sirven como reserva de riqueza o botin facil de ocultar.",
        weight: "Ligera",
        value: "25 taleros",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Valioso",
        notes: buildItemCatalogNotes("Mercancia de alto valor en poco volumen.", ["Valioso"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 1
    },
    {
        templateId: "treasure-gemstones",
        name: "Gemas",
        category: "treasure",
        stackable: true,
        isCustom: false,
        description: "Piedras talladas o en bruto que concentran valor y resultan faciles de transportar.",
        weight: "Ligera",
        value: "50 taleros",
        slot: "none",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Valioso",
        notes: buildItemCatalogNotes("Bien comercial o tesoro compacto.", ["Valioso"]),
        grantedActions: [],
        modifiers: [],
        defaultQuantity: 1
    },
    {
        templateId: "artifact-generic",
        name: "Artefacto",
        category: "artifact",
        stackable: false,
        isCustom: false,
        description: "Artefacto mistico de origen desconocido.",
        weight: "",
        value: "",
        slot: "artifact",
        attackAttribute: undefined,
        damageFormula: "",
        protectionFormula: "",
        qualities: "Mistico",
        notes: buildItemCatalogNotes("Artefacto mistico de origen desconocido.", ["Mistico"]),
        grantedActions: [],
        modifiers: []
    }
];
const ARMOR_CATALOG_ORDER = [
    "Armadura ligera", "Armadura oculta", "Capa de la Ordo", "Coraza de escaldo", "Cuero tachonado",
    "Hilo de seda", "Piel de lobo", "Ropajes de bruja", "Túnica bendita", "Armadura media",
    "Armadura de cuervo", "Armadura lamelar", "Coraza de seda lacada", "Cota de malla de doble",
    "Armadura pesada", "Armadura completa", "Armadura completa de templario", "Armadura de la furia",
    "Armadura de placas", "Armadura de placas pansar"
];
export const ITEM_CATALOG = [...WEAPON_ITEM_TEMPLATES, ...OTHER_ITEM_TEMPLATES]
    .filter((template) => template.templateId !== "artifact-generic")
    .sort((left, right) => {
    if (left.category !== "armor" || right.category !== "armor")
        return 0;
    return ARMOR_CATALOG_ORDER.indexOf(left.name) - ARMOR_CATALOG_ORDER.indexOf(right.name);
});
export { WEAPON_QUALITY_OPTIONS };
export function createInventoryItemFromTemplate(template) {
    return {
        ...template,
        id: `${template.templateId}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        quantity: template.defaultQuantity ?? 1,
        equipped: false
    };
}
export function createCustomInventoryItem(category = "gear") {
    const isWeapon = category === "weapon";
    const isArmor = category === "armor";
    return {
        id: `custom-item-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        name: isWeapon ? "Arma personalizada" : isArmor ? "Armadura personalizada" : "Objeto personalizado",
        category,
        quantity: 1,
        stackable: false,
        isCustom: true,
        description: "",
        weight: "",
        value: "",
        equipped: false,
        slot: isWeapon ? "mainHand" : isArmor ? "armor" : "none",
        attackAttribute: isWeapon ? "diestro" : undefined,
        damageFormula: "",
        protectionFormula: isArmor ? "1d4" : "",
        qualities: isArmor ? "Ligera" : "",
        notes: "",
        grantedActions: [],
        modifiers: []
    };
}
