from __future__ import annotations

import json
import re
from pathlib import Path
from xml.etree import ElementTree
from zipfile import ZipFile


ROOT = Path(__file__).resolve().parents[1]
COMPENDIUM_SOURCE = ROOT / "packages/shared/src/symbaroumCompendium.ts"
SUMMARY_DOCUMENT = ROOT / "docs/Summaries/Habilidades, poderes y rituales.docx"
TYPESCRIPT_OUTPUT = ROOT / "packages/shared/src/ritualSummaries.generated.ts"
JAVASCRIPT_OUTPUT = ROOT / "packages/shared/src/ritualSummaries.generated.js"

WORD_NAMESPACE = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
NAMESPACES = {"w": WORD_NAMESPACE}
HEADING_ALIASES = {
    "Grilletes rúnicos": "Grilletes del destino",
}


def read_catalogue_ritual_names() -> list[str]:
    source = COMPENDIUM_SOURCE.read_text(encoding="utf-8")
    encoded_names = re.findall(r'makeCapability\("ritual",\s*("(?:[^"\\]|\\.)*")', source)
    names = [json.loads(encoded_name) for encoded_name in encoded_names]
    if len(names) != 66:
        raise RuntimeError(f"Se esperaban 66 rituales en el catálogo y se encontraron {len(names)}")
    return names


def read_document_paragraphs() -> list[tuple[str, str]]:
    with ZipFile(SUMMARY_DOCUMENT) as archive:
        document = ElementTree.fromstring(archive.read("word/document.xml"))

    paragraphs: list[tuple[str, str]] = []
    for paragraph in document.findall(".//w:body/w:p", NAMESPACES):
        text = "".join(node.text or "" for node in paragraph.findall(".//w:t", NAMESPACES))
        text = re.sub(r"\s+", " ", text).strip()
        if not text:
            continue

        style_node = paragraph.find("./w:pPr/w:pStyle", NAMESPACES)
        style = style_node.get(f"{{{WORD_NAMESPACE}}}val", "") if style_node is not None else ""
        paragraphs.append((style, text))

    return paragraphs


def collect_heading_descriptions(paragraphs: list[tuple[str, str]]) -> dict[str, str]:
    descriptions: dict[str, str] = {}

    for index, (style, text) in enumerate(paragraphs):
        if style != "Heading3" or not text.endswith(":"):
            continue

        heading = text[:-1].strip()
        content: list[str] = []
        for next_style, next_text in paragraphs[index + 1 :]:
            if next_style.startswith("Heading"):
                break
            content.append(next_text)

        if content and heading not in descriptions:
            descriptions[heading] = "\n\n".join(content)

    return descriptions


def render_mapping(entries: dict[str, str], *, typescript: bool) -> str:
    declaration = (
        "export const RITUAL_SUMMARIES: Record<string, string> = {"
        if typescript
        else "export const RITUAL_SUMMARIES = {"
    )
    lines = ["// Generated by scripts/generate_ritual_summaries.py. Do not edit manually.", declaration]
    for name, description in entries.items():
        lines.append(f"  {json.dumps(name, ensure_ascii=False)}: {json.dumps(description, ensure_ascii=False)},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> None:
    ritual_names = read_catalogue_ritual_names()
    descriptions = collect_heading_descriptions(read_document_paragraphs())
    entries: dict[str, str] = {}
    missing: list[str] = []

    for ritual_name in ritual_names:
        heading = HEADING_ALIASES.get(ritual_name, ritual_name)
        description = descriptions.get(heading)
        if not description:
            missing.append(f"{ritual_name} (encabezado esperado: {heading})")
            continue
        entries[ritual_name] = description

    if missing:
        raise RuntimeError("Faltan descripciones para: " + ", ".join(missing))

    TYPESCRIPT_OUTPUT.write_text(render_mapping(entries, typescript=True), encoding="utf-8")
    JAVASCRIPT_OUTPUT.write_text(render_mapping(entries, typescript=False), encoding="utf-8")
    print(f"Generadas {len(entries)} descripciones de rituales")


if __name__ == "__main__":
    main()
